In [3]:
import numpy as np

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [9]:
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [19]:
a, b, c = map(int,input("Enter two numbers").split())
x =np.random.random(a).reshape(b,c)
print(x.mean())

0.6186760076128472


Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.


Eg.-

[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]

In [25]:
a = np.ones((4,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
def borderArray(a,b):
    x = np.ones((a,b))
    x[1:-1,1:-1] = 0
    return x

borderArray(11,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
s = np.arange(24).reshape(6,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
s[0:2,-1]

array([3, 7])

Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [59]:
x = np.linspace(0,1,12)[1:-1]
x


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [69]:
np.eye(3)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [82]:
z = np.zeros((5,5))
z+=np.arange(5)

Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [93]:
arr = np.random.randint(1,100,(10,2))
point = np.array([2,3])
#print(arr)
np.sqrt(np.sum((arr-point)**2,axis=1)).astype(int)

array([86, 19, 71, 72, 78, 84, 47, 18, 18, 50])

Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [106]:
#np.array((6,7,8))
a  = np.zeros((6,7,8))
a

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [107]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

Q-9: Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

Input:

1 2 3 4 -8 -10
Output:

[-10.  -8.   4.   3.   2.   1.]

In [112]:
a = input().strip().split()
np.array(a[::-1]).astype(float)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

Q-10: Elements count
Count the number of elements of a numpy array.

Example 1:

Input:

np.array([])
Output:

elements_count :  0
Example 2:

Input:

np.array([1, 2])
Output:

elements_count :  2

In [120]:
a = np.array([1,2])
print("elements_count : ",a.size)

elements_count :  2


Q-11: Softmax function
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

σ(z⃗ )i=ezi∑Kj=iezj 

https://en.wikipedia.org/wiki/Softmax_function

Example 1:

Input:

[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
Output:

[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
Example 2:

Input:

[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
Output:

[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]

In [128]:
def softmax(arr):
    if type(arr)!= np.ndarray:
        raise TypeError('Requires Numpy Array')
    elif arr.ndim > 1:
        raise TypeError("Required 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

softmax(np.array([2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]))

array([0.172286  , 0.13501996, 0.13501996, 0.28763416, 0.13501996,
       0.13501996])

Q-12: Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

Example 1:

Input:

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

In [140]:
def VerticleStatck(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError('Required Numpy Array')
    return np.vstack(args)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c = np.random.random((2,5))

VerticleStatck(a,b,c)



array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.44572291, 0.95182845, 0.56512083, 0.89898919, 0.31758031],
       [0.23928301, 0.74230399, 0.0529679 , 0.79643461, 0.0486315 ]])

In [136]:
a = np.repeat(1,10).reshape(2,-1)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q-13: Dates

Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.